/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#00372e",
        "on-secondary-container": "#5a666d",
        "on-primary-fixed": "#001945",
        "primary-fixed-dim": "#b0c6ff",
        "surface-container": "#eceef0",
        "tertiary": "#00201a",
        "outline-variant": "#c6c5d4",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#002c6e",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#b0c6ff",
        "secondary": "#546067",
        "primary-fixed": "#d9e2ff",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#00ab93",
        "on-primary": "#ffffff",
        "secondary-fixed": "#d7e4ec",
        "on-tertiary-fixed": "#00201a",
        "on-primary-fixed-variant": "#00429c",
        "on-surface-variant": "#454652",
        "secondary-container": "#d7e4ec",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "outline": "#767683",
        "tertiary-fixed": "#68fadd",
        "tertiary-fixed-dim": "#44ddc1",
        "surface-container-high": "#e6e8ea",
        "primary": "#001944",
        "secondary-fixed-dim": "#bbc8d0",
        "on-tertiary-fixed-variant": "#005145",
        "on-secondary-fixed": "#111d23",
        "surface-bright": "#f7f9fb",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3c494f",
        "surface-tint": "#2b5bb5",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "background": "#f7f9fb",
        "on-primary-container": "#6b95f3",
        "on-background": "#191c1e",
        "inverse-surface": "#2d3133",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "stratos-navy": "#1A237E",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};
